name: SpeedScanX CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build, Audit & Check SpeedScanX
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Repository auschecken
        uses: actions/checkout@v4

      - name: ⚙️ Node.js Umgebung einrichten
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: 📦 Abhängigkeiten installieren
        run: npm install

      - name: 🛡️ Sicherheitsprüfung (npm audit)
        run: npm audit --audit-level=moderate || true

      - name: 🔍 README-Badges prüfen
        run: |
          if grep -q "bylickilabs/speedScanX/README.md" README.md; then
            echo "✅ Badge-Link gefunden"
          else
            echo "❌ Badge-Link fehlt oder falsch"
            exit 1
          fi

      - name: 🧪 Node-Version prüfen
        run: node -v

      - name: 🧹 Projektverzeichnis prüfen
        run: ls -la
