name: SpeedScanX CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: Node.js einrichten
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Abhängigkeiten installieren
        run: npm install

      - name: Build-Prozess durchführen
        run: npm run build || echo "Kein Build-Skript vorhanden"

      - name: Tests durchführen
        run: npm test || echo "Keine Tests vorhanden"

      - name: Linting
        run: npm run lint || echo "Kein Linting vorhanden"

      - name: Node-Version anzeigen
        run: node -v
