name: SpeedScanX CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: Node.js einrichten
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Abhängigkeiten installieren
        run: npm install

      - name: README überprüfen
        run: |
          if grep -q "bylickilabs/speedScanX/README.md" README.md; then
            echo "✅ README enthält Badge-Referenz"
          else
            echo "❌ Badge-Link fehlt oder falsch"
            exit 1
          fi

      - name: Node-Version anzeigen
        run: node -v
